{% set name = "muon" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scverse/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e990801fedd165b20c5d967d3466b04108f2f88c513c98ea4dfd2222d5f8a8c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2,<4
  run:
    - numpy
    - pandas
    - matplotlib-base
    - seaborn
    - h5py
    - anndata
    - scanpy
    - scikit-learn
    - umap-learn
    - tqdm
    - mudata
    - numba
    - natsort
    - protobuf
    - python >=3.6

test:
  imports:
    - muon

about:
  home: https://github.com/scverse/muon
  summary: Multimodal omics analysis framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grst
    - gtca
