{% set name = "muon" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scverse/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dd086bb236fd23563deac498aa51524707fcedecd55af1d67774ef4b26559317

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=2,<4
  run:
    - numpy
    - pandas
    - matplotlib-base
    - seaborn
    - h5py
    - anndata
    - scanpy
    - scikit-learn
    - umap-learn
    - tqdm
    - mudata
    - numba
    - natsort
    - protobuf
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - muon

about:
  home: https://github.com/scverse/muon
  summary: Multimodal omics analysis framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grst
    - gtca
