{% set python_min = "3.12" %}
{% set name = "muon" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scverse/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a1f444d26ce39b9967f69eb5068b1838df7d1249dbadcb096fedf274f2e82c01

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - anndata
    - h5py
    - matplotlib-base
    - mudata
    - numba
    - numpy
    - pandas >=1
    - protobuf
    - scanpy
    - scikit-learn
    - scverse-misc >=0.1.1
    - seaborn
    - session-info2
    - umap-learn
    - tqdm
    - python >={{ python_min }}

test:
  imports:
    - muon

about:
  home: https://github.com/scverse/muon
  summary: Multimodal omics analysis framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ilia-kats
    - ilan-gold
    - flying-sheep
    - grst
    - gtca
